### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by IamEinstein1** [elect-app/code#1]
@TarunKumar29 There is seriously a major problem in this\
I(@IamEinstein1 ) Cloned  the repo and then added some js for the `about page` in `js/about.js`
But it doesnt work
> Can you tell what to do ?

**Comment by TarunKumar29** [comment]
Show me the code (Not here) and the problem

**Comment by TarunKumar29** [comment]
The issue is closed as there wasn't enough information
